### ISSUE TITLE
Segmentation fails due to out-of-memory issue in low memory environments

### ISSUE THREAD

**Issue by mousa-saeed** [SCAN-NRAD/DL-DiReCT#2]
Hello,

I am trying to run the package on an scan that I have. the package run smoothly till it reaches the segmentation where it returns "segmentation fails", i uncommented the  shell command so I can see the error exactly. this is what i got.

FileNotFoundError: No such file or no access: '/content/drive/MyDrive/[PROJECT]/seg_Left-Cerebral-White-Matter.nii.gz'
ERROR: DiReCT failed

i have checked my files and i have no output with the same name, i am guessing that the package should have produced it while running. 

what part of it is responsible for this file (seg_Left-Cerebral-White-Matter.nii.gz)

Thanks in advance

**Comment by mrunibe** [comment]
Hi,

This file should be created by the first, deep learning-based segmentation part. Do you see any other error preceding the "segmentation failed"?

A common issue is memory problems (either on the GPU or CPU) which might be caused by a too-large input volume. Is your scan pre-processed, and if not, did you use the `--bet` option to remove the skull?

Do you run it on a GPU and how much memory is available?

**Comment by mousa-saeed** [comment]
Hi, 

Thank you for the prompt reply.
there isnt any other error preceding it. 
I am running it on google colab, the memory seems ok. 
I use --bet to remove the skull and I get 4 files, (T1 norm, noskull, cropped, mask).

the command:
!dl+direct --subject 001 --bet /content/drive/MyDrive/Hipposeg/patient_data/80100000_t1w_3d_tfe_nyul.nii.gz /content/output

this is the output of the command i run:

If you are using DL+DiReCT in your research, please cite:
	Rebsamen, M, Rummel, C, Reyes, M, Wiest, R, McKinley, R.
	Direct cortical thickness estimation using deep learning‐based anatomy segmentation and cortex parcellation.
	Human Brain Mapping. 2020; 41: 4804-4814. https://doi.org/10.1002/hbm.25159

Input: (1.0000019, 0.9375, 0.9375) [LAS]
Resampling
Brain extraction using HD-BET [https://doi.org/10.1002/hbm.24750] ...
File: /content/output/T1w_norm.nii.gz
preprocessing...
image shape after preprocessing:  (171, 171, 171)
prediction (CNN id)...
0
1
2
3
4
running postprocessing... 
exporting segmentation...
1
loading checkpoint /content/DL-DiReCT/src/../model/v0_f1.pth
2
Axis 0..............
tcmalloc: large alloc 2568134656 bytes == 0x135292000 @  0x7f8dd48d51e7 0x7f8dd21260ce 0x7f8dd217ccf5 0x7f8dd222586d 0x7f8dd222617f 0x7f8dd22262d0 0x4ba72b 0x7f8dd2167944 0x58f67f 0x50ff13 0x5b4ee6 0x58ff2e 0x510325 0x5b575e 0x58ff2e 0x50d482 0x5b4ee6 0x6005a3 0x607796 0x60785c 0x60a436 0x64db82 0x64dd2e 0x7f8dd44d2c87 0x5b636a
Axis 1...............
tcmalloc: large alloc 2697469952 bytes == 0x7f892737e000 @  0x7f8dd48d51e7 0x7f8dd21260ce 0x7f8dd217ccf5 0x7f8dd222586d 0x7f8dd222617f 0x7f8dd22262d0 0x4ba72b 0x7f8dd2167944 0x58f67f 0x50ff13 0x5b4ee6 0x58ff2e 0x510325 0x5b575e 0x58ff2e 0x50d482 0x5b4ee6 0x6005a3 0x607796 0x60785c 0x60a436 0x64db82 0x64dd2e 0x7f8dd44d2c87 0x5b636a
Axis 2.................
tcmalloc: large alloc 3048505344 bytes == 0x7f885b7ce000 @  0x7f8dd48d51e7 0x7f8dd21260ce 0x7f8dd217ccf5 0x7f8dd222586d 0x7f8dd222617f 0x7f8dd22262d0 0x4ba72b 0x7f8dd2167944 0x58f67f 0x50ff13 0x5b4ee6 0x58ff2e 0x510325 0x5b575e 0x58ff2e 0x50d482 0x5b4ee6 0x6005a3 0x607796 0x60785c 0x60a436 0x64db82 0x64dd2e 0x7f8dd44d2c87 0x5b636a
/content/DL-DiReCT/src/../dl+direct.sh: line 120:  1568 Killed                  python ${SCRIPT_DIR}/DeepSCAN_Anatomy_Newnet_apply.py ${MODEL_ARGS} "${IN_VOLUME_CROP}" "${DST}" "${SUBJECT_ID}"
ERROR: Segmentation failed

**Comment by mrunibe** [comment]
Hi,

This seems indeed to be a (CPU-)memory issue. The process is likely killed for allocating too much RAM. Unfortunately, it requires some more memory (approx. 16 GB) to run.

Maybe there is an option to run the notebook with more memory in colab?

**Comment by mousa-saeed** [comment]
Hi, 

I am running with a GPU.
if that could be the case, maybe I can try to run the python script responsible only for segmentation? since its the script that fails now.

or maybe reduce the required memory, like running it for one axis only?

**Comment by mrunibe** [comment]
Hi,

It likely happens when ensembling the results which is quite memory hungry with so many labels.

However, I just added a workaround (c817050ee959afa71fc3bed943e2694beaeb3a17): You can use the `--lowmem` option to reduce memory consumption. See also [FAQ](https://github.com/SCAN-NRAD/DL-DiReCT/blob/main/doc/faq.md#what-are-the-system-requirements-to-run-dldirect)

Just pull the latest update and run again with `--lowmem` to try.

**Comment by mousa-saeed** [comment]
Hi,
I tried it, still ran into the same error.
I did a work around where I adjusted the script to segment only one axis instead of 3. it worked but I do not know how much are the results different. do you have any experience with that?

**Comment by mrunibe** [comment]
In principle, it should work but you might get less reliable results (especially if image quality is not optimal). For best results, I would still recommend trying to get it run over all axes. Looks like it's possible to get VMs with 25GB of memory on colab, that should be enough.

**Comment by mrunibe** [comment]
The last update (58599ed5a91c6774b9bcbf94fa7f8212e8b07708) should further reduce memory requirements.

**Comment by mousa-saeed** [comment]
Thanks, tried it and now it works!
